//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System; 
public class TestTeam : MonoBehaviour{
	public TestTeam () {
		string tName = "a";
		for (int i = 0; i < 10; i++) {
			//Debug.Log(Team.AddNewTeam (tName));
			if(i%2 == 0) {
				tName += "a";
			} else {
				tName += "b";
			}
		}
		//Debug.Log (Team.GetTeam(0).GetTeamName());
		//Debug.Log (Team.GetTeam(5).GetTeamName());
		//Debug.Log (Team.GetTeam(9).GetTeamName());
		//Debug.Log (Team.GetTeam(1).GetTeamName());
		//Debug.Log (Team.HasTeam("aa"));
		Team.GetTeam (1).SetTeamName("ab");
		//Debug.Log (Team.HasTeam("aa"));
		//Debug.Log (Team.HasTeam("ab"));
		string team9 = Team.GetTeam (9).GetTeamName();
		Team.GetTeam (9).SetTeamName("yellow");
		//Debug.Log (Team.HasTeam("yellow"));
		//Debug.Log (Team.HasTeam(team9));
		Team.RemoveTeam (3);
		//Debug.Log(Team.HasTeam(3));
		//Debug.Log (Team.AddNewTeam("Gold"));
		Team.RemoveTeam (0);
		Team.RemoveTeam (1);
		//Debug.Log(Team.AddNewTeam("Cyan"));
		//Debug.Log (Team.AddNewTeam("Red"));
		Team.RemoveTeam (9);
		//Debug.Log (Team.AddNewTeam("Purple"));
		/*for (int i = 0; i < 10; i++) {
			//Debug.Log (Team.HasTeam(i));
		}*/
	}
}